name: Build, Test, and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java (or your environment)
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    - name: SonarQube Scan
      run: mvn sonar:sonar -Dsonar.host.url=https://your-sonarqube-url

    - name: Nexus IQ Scan
      run: mvn org.sonatype.plugins:nexus-iq-maven-plugin:check

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Upload to Artifactory
      run: docker push your-artifactory-url/your-image-name

    - name: Login to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push to ACR
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/your-image-name

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: your-app-name
        slot-name: production
        images: ${{ secrets.ACR_LOGIN_SERVER }}/your-image-name
